Models/Color.cs
namespace EverythingSucks.Models
{
    public class Color
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public string Name { get; set; }
        public string ColorCode { get; set; }

        public virtual ICollection<ProductColor>? ProductColors { get; set; }
    }
}

Controllers/ColorController.cs
using EverythingSucks.Data;
using EverythingSucks.Models;
using EverythingSucks.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.WebSockets;

namespace EverythingSucks.Controllers
{
    public class ColorController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ColorController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> IndexAsync()
        {
            IEnumerable<Color> colors = await _context.Colors.ToListAsync();
            return View(colors);
        }

        // GET: Color/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Color/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateColorViewModel colorVM)
        {
            if (ModelState.IsValid)
            {
                var color = new Color
                {
                    Name = colorVM.Name,
                    ColorCode = colorVM.ColorCode,
                };

                _context.Add(color);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Failed to create color");
            }

            return View(colorVM);
        }
    }
}

Views/Color/Create.cshtml
@using EverythingSucks.ViewModels
@model CreateColorViewModel

@{
    ViewData["Title"] = "Create Color";
}

<h2>Create Color</h2>

<form asp-controller="Color" asp-action="Create" method="post">
    <div class="form-group mb-2">
        <label asp-for="Name">Color name</label>
        <input asp-for="Name" id="Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group mb-2">
        <label asp-for="ColorCode">Color code</label>
        <input asp-for="ColorCode" id="ColorCode" class="form-control">
        <span asp-validation-for="ColorCode" class="text-danger"></span>
    </div>
    <div>
        <div class="col-md-2">
            <button type="submit" id="submitBtn" class="btn btn-primary">Create</button>
        </div>
    </div>
</form>

Views/Color/Index.cshtml
@model IEnumerable<Color>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4">
            <p>@item.Name</p>
            <div style="background-color:@item.ColorCode; width:100px; height:100px;"></div>
            <p>@item.ColorCode</p>
        </div>
    }
</div>